try{

    const m=1;
    const n=m+z;
    console.log(m+z)
} catch(err) {
    console.log(err.name)
}